version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: ms_mongo
    environment:
      MONGO_INITDB_DATABASE: bd_seguridad
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:15
    container_name: ms_postgres
    environment:
      POSTGRES_DB: bd_articulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5439:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    container_name: ms_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_movimiento
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mongo_data:
  pg_data:
  mysql_data:
